kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: matias-quarkus-openshift
  namespace: default
  uid: 4292f9e8-a826-4a15-afff-1e7b7b5430d7
  resourceVersion: '14278211'
  creationTimestamp: '2026-01-22T14:43:03Z'
  labels:
    app: matias-quarkus-openshift
    app.kubernetes.io/component: matias-quarkus-openshift
    app.kubernetes.io/instance: matias-quarkus-openshift
    app.kubernetes.io/name: matias-quarkus-openshift
    app.kubernetes.io/part-of: matias-quarkus-openshift-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/MatiasWinter/matias-quarkus-openshift/'
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: 'true'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2026-01-22T14:43:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:tls':
            .: {}
            'f:insecureEdgeTerminationPolicy': {}
            'f:termination': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2026-01-22T14:43:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
spec:
  host: matias-quarkus-openshift-default.apps-crc.testing
  to:
    kind: Service
    name: matias-quarkus-openshift
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: matias-quarkus-openshift-default.apps-crc.testing
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2026-01-22T14:43:03Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps-crc.testing
